{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mygen.serviceAccountName" . }}
  labels:
{{ include "mygen.labels" . | indent 4 }}
{{- end -}}
