apiVersion: v1
kind: Service
metadata:
  name: hpa-api-svc
  labels:
{{ include "myhpa.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: hpa-api
    
